---
- name: "update local apt repo."
  become: true 
  apt:
    update_cache: yes

- name: "upgrade apt packages"
  become: true
  apt:
    upgrade: yes

- name: "Install dependencies [ nodejs and npm]."
  become: true 
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Creates backend app directory"
  file:
    path: ~/backend_app_dir
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend_app_dir

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend_app_dir
    npm i
- name: "Executing Node app with PM2"
  shell: |
    cd ~/backend_app_dir/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save